import { existsSync, readFileSync } from 'fs';
import { join } from 'path';

/**
 * Load Supabase env for tests.
 * Priority:
 * 1) Existing process.env values.
 * 2) Keys generated by `supabase start` in infra/supabase/.temp/keys.json.
 * 3) Fallback dev JWTs used for local testing.
 */
export function ensureSupabaseEnv(): void {
  if (!process.env.SUPABASE_URL) {
    process.env.SUPABASE_URL = 'http://localhost:54321';
  }

  const keysPathCandidates = [
    join(process.cwd(), 'infra/supabase/.temp/keys.json'),
    join(process.cwd(), '..', '..', 'infra/supabase/.temp/keys.json'), // when tests run from app dir
  ];

  let keys: { anon_key?: string; service_role_key?: string; jwt_secret?: string } | null = null;
  for (const p of keysPathCandidates) {
    if (existsSync(p)) {
      try {
        keys = JSON.parse(readFileSync(p, 'utf8'));
        break;
      } catch {
        // ignore parse errors and continue
      }
    }
  }

  const fallbackAnon =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzY1MDIyMTIxLCJleHAiOjIxNDc0ODM2NDd9.d2GDdV71EQRtmmtZ4HBHMUfRE2rvACyajFRbyNnhmcQ';
  const fallbackService =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE3NjUwMjIxMjEsImV4cCI6MjE0NzQ4MzY0N30.IhqAZz2fN6eIYahPaXO1mTWkEkdBeFXjpQuYzUSZ8LM';

  process.env.SUPABASE_ANON_KEY ||= keys?.anon_key || fallbackAnon;
  process.env.SUPABASE_SERVICE_ROLE_KEY ||= keys?.service_role_key || fallbackService;
  process.env.SUPABASE_JWT_SECRET ||= keys?.jwt_secret || 'dev-jwt-secret';
}
