import { existsSync, readFileSync } from 'fs';
import { join } from 'path';

/**
 * Load Supabase env for tests.
 * Priority:
 * 1) Existing process.env values.
 * 2) Keys generated by `supabase start` in infra/supabase/.temp/keys.json.
 * 3) Fallback dev JWTs used for local testing.
 */
export function ensureSupabaseEnv(): void {
  // In CI, we must relies on injected secrets. Never fallback to localhost as it confuses tests.
  if (process.env.CI) {
    if (!process.env.SUPABASE_URL) {
      console.warn('WARNING: SUPABASE_URL is missing in CI environment!');
    }
    return;
  }

  if (!process.env.SUPABASE_URL) {
    process.env.SUPABASE_URL = 'http://127.0.0.1:54321';
  }

  const keysPathCandidates = [
    join(process.cwd(), 'infra/supabase/.temp/keys.json'),
    join(process.cwd(), '..', '..', 'infra/supabase/.temp/keys.json') // when tests run from app dir
  ];

  let keys: {
    anon_key?: string;
    service_role_key?: string;
    jwt_secret?: string;
  } | null = null;
  for (const p of keysPathCandidates) {
    if (existsSync(p)) {
      try {
        keys = JSON.parse(readFileSync(p, 'utf8'));
        break;
      } catch {
        // ignore parse errors and continue
      }
    }
  }

  // We strictly use the keys from the environment (loaded via config pckg or whatever loaded them)
  // or the ones found specifically in the temp file if we are still relying on that for some reason (which we shouldn't for cloud).
  // For Cloud switch, we trust the env vars are already loaded or will be loaded by `loadConfig`.
  // However, `process.env` might need to be populated if not already.
  // The `loadConfig` call in tests usually happens AFTER this function or inside it.

  // Actually, let's just ensure if keys are missing we fail, or we trust they are there.
  // Since we are moving to cloud, we don't need 'sb_publishable...' fallbacks.

  if (keys) {
    process.env.SUPABASE_ANON_KEY = keys.anon_key;
    process.env.SUPABASE_SERVICE_ROLE_KEY = keys.service_role_key;
    process.env.SUPABASE_JWT_SECRET = keys.jwt_secret;
  }
}
