-- Create ENUM for session status
CREATE TYPE session_status AS ENUM ('in_progress', 'completed', 'aborted');

-- Create SESSIONS table
CREATE TABLE sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    planned_session_id UUID REFERENCES planned_sessions(id) ON DELETE SET NULL,
    start_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    end_time TIMESTAMPTZ,
    status session_status NOT NULL DEFAULT 'in_progress',
    metrics JSONB DEFAULT '{}'::jsonb, -- Store summary stats: distance, duration, avg_pace, elevation_gain
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for sessions
CREATE INDEX idx_sessions_user_id ON sessions(user_id);
CREATE INDEX idx_sessions_start_time ON sessions(start_time DESC);

-- Enable RLS for sessions
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;

-- RLS Policies for sessions
-- Users can view their own sessions
CREATE POLICY "Users can view own sessions"
    ON sessions FOR SELECT
    USING (auth.uid() = user_id);

-- Users can insert their own sessions
CREATE POLICY "Users can create own sessions"
    ON sessions FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Users can update their own sessions
CREATE POLICY "Users can update own sessions"
    ON sessions FOR UPDATE
    USING (auth.uid() = user_id);

-- Users can delete their own sessions
CREATE POLICY "Users can delete own sessions"
    ON sessions FOR DELETE
    USING (auth.uid() = user_id);


-- Create SESSION_POINTS table
-- Using BIGINT for ID because point volume can be massive
CREATE TABLE session_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    timestamp TIMESTAMPTZ NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    alt DOUBLE PRECISION,
    heart_rate INTEGER,
    data JSONB DEFAULT '{}'::jsonb -- For other metrics: cadence, power, speed, etc.
);

-- Indexes for session_points
-- Optimizing for retrieving points by session in order
CREATE INDEX idx_session_points_session_id_timestamp ON session_points(session_id, timestamp);

-- Enable RLS for session_points
ALTER TABLE session_points ENABLE ROW LEVEL SECURITY;

-- RLS Policies for session_points
-- We use a USING clause that checks the parent session's user_id
-- This avoids storing user_id on every point (space saving) but requires a join check.
CREATE POLICY "Users can view points of own sessions"
    ON session_points FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM sessions s
            WHERE s.id = session_points.session_id
            AND s.user_id = auth.uid()
        )
    );

-- Users can insert points for their own sessions
CREATE POLICY "Users can insert points for own sessions"
    ON session_points FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM sessions s
            WHERE s.id = session_points.session_id
            AND s.user_id = auth.uid()
        )
    );
